const REPO='gabsinsider/CutCutAi'; let clips=[];
const $=s=>document.querySelector(s); const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item,.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')}));
function issueUrl(title,body,labels='live-request'){return `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}&labels=${encodeURIComponent(labels)}`}
$('#live-form').addEventListener('submit',e=>{e.preventDefault();const url=$('#live-url').value.trim();window.open(issueUrl('[LIVE] Processar transmissão',`## Link da live\n${url}\n\n## Configuração\n- Captura inicial: 180 segundos\n`),'_blank','noopener');toast('Finalize o envio da Issue no GitHub.')});
$('#live-url').addEventListener('input',e=>{const v=e.target.value.toLowerCase();let n='Plataforma compatível com yt-dlp';if(v.includes('youtu'))n='YouTube detectado';else if(v.includes('tiktok'))n='TikTok detectado';else if(v.includes('facebook')||v.includes('fb.watch'))n='Facebook detectado';else if(v.includes('twitch'))n='Twitch detectado';$('#platform-hint').textContent=n});
function escapeHtml(t){const p=document.createElement('p');p.textContent=t;return p.innerHTML}
function clipCard(c,i){const a=c.asset_url||'#',d=new Date(c.created_at).toLocaleDateString('pt-BR');return `<article class="clip-card"><div class="thumb">${c.thumbnail_url?`<img src="${c.thumbnail_url}" alt="">`:''}<span class="score">#${i+1} · ${Math.round(c.score)}</span></div><div class="clip-body"><h3>${escapeHtml(c.title||'Corte sem título')}</h3><div class="meta"><span>${Math.round(c.duration||60)}s</span><span>${d}</span></div><p class="tags">${(c.hashtags||[]).join(' ')}</p><div class="card-actions"><a href="${a}" ${a==='#'?'aria-disabled="true"':'target="_blank"'}>Assistir</a><button data-edit="${c.id}">Editar</button></div></div></article>`}
async function loadRanking(){try{const r=await fetch('data/ranking.json?ts='+Date.now());if(!r.ok)throw new Error();clips=(await r.json()).clips||[];$('#ranking-grid').innerHTML=clips.map(clipCard).join('');$('#empty-state').hidden=clips.length>0;$('#clip-select').innerHTML='<option value="">Selecione…</option>'+clips.map(c=>`<option value="${c.id}">${escapeHtml(c.title)}</option>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(b.dataset.edit)))}catch{$('#empty-state').hidden=false;toast('Não foi possível atualizar o ranking.')}}
function openEditor(id){document.querySelector('[data-view="editor"]').click();$('#clip-select').value=id;updatePreview()}
function updatePreview(){const c=clips.find(x=>x.id===$('#clip-select').value),v=$('#preview'),stage=$('#preview-stage');if(c?.asset_url){v.src=c.asset_url;stage.hidden=false;$('#video-placeholder').hidden=true}else{v.removeAttribute('src');stage.hidden=true;$('#video-placeholder').hidden=false}updateCaptionPreview()}
function updateCaptionPreview(){const box=$('#caption-preview'),style=$('#caption-style').value,position=$('#caption-position').value;box.hidden=style==='none';box.style.color=$('#caption-color').value;box.style.fontSize=`${Math.round(Number($('#caption-size').value)*.42)}px`;box.dataset.position=position;box.textContent=$('#caption-emphasis').checked?'Sua legenda aparece AQUI':'Sua legenda aparece aqui';$('#caption-size-value').textContent=$('#caption-size').value;$('#caption-controls').hidden=style==='none'}
['caption-style','caption-color','highlight-color','caption-position','caption-size','caption-emphasis'].forEach(id=>$(`#${id}`).addEventListener('input',updateCaptionPreview));
$('#clip-select').addEventListener('change',updatePreview);$('#refresh').addEventListener('click',loadRanking);$('#resolution').addEventListener('change',e=>$('#quality-warning').hidden=e.target.value!=='2160');
$('#edit-form').addEventListener('submit',e=>{e.preventDefault();const id=$('#clip-select').value;if(!id)return;const body=`## Corte\n${id}\n\n## Edição\n- Legenda: ${$('#caption-style').value}\n- Cor: ${$('#caption-color').value}\n- Destaque: ${$('#highlight-color').value}\n- Posição: ${$('#caption-position').value}\n- Tamanho: ${$('#caption-size').value}\n- Ênfase automática: ${$('#caption-emphasis').checked?'sim':'não'}\n- Filtro: ${$('#filter').value}\n- Resolução: ${$('#resolution').value}`;window.open(issueUrl(`[EDIT] Exportar ${id}`,body,'edit-request'),'_blank','noopener');toast('Finalize o pedido de edição no GitHub.')});
updateCaptionPreview();loadRanking();
