const REPO='gabsinsider/CutCutAi'; const WORKER='https://cutcutai-production.up.railway.app'; let clips=[]; let captionTrack=[]; let statusTimer=null;
const $=s=>document.querySelector(s); const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item,.view').forEach(e=>e.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')}));
function issueUrl(title,body,labels='live-request'){return `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}&labels=${encodeURIComponent(labels)}`}
function setLiveState(data={}){const running=!!data.running,btn=$('#live-submit'),stop=$('#live-stop'),status=$('#live-status');btn.disabled=running;btn.textContent=running?'Live em processamento':'Analisar live';stop.hidden=!running;status.hidden=false;if(running){status.textContent='● Acompanhando a live continuamente';status.dataset.state='running'}else{status.textContent='Pronto para receber uma live';status.dataset.state='idle'}}
async function workerStatus(){try{const r=await fetch(`${WORKER}/status`,{cache:'no-store'});if(!r.ok)throw new Error();const data=await r.json();setLiveState(data);return data}catch{const status=$('#live-status');status.hidden=false;status.textContent='Worker temporariamente indisponível';status.dataset.state='error';return null}}
function beginStatusPolling(){clearInterval(statusTimer);statusTimer=setInterval(workerStatus,10000)}
$('#live-form').addEventListener('submit',async e=>{e.preventDefault();const url=$('#live-url').value.trim(),btn=$('#live-submit');btn.disabled=true;btn.textContent='Iniciando…';try{const r=await fetch(`${WORKER}/live/start`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Falha ao iniciar');setLiveState(data);beginStatusPolling();toast('Live iniciada. O CutCutAi está acompanhando a transmissão.')}catch(err){btn.disabled=false;btn.textContent='Analisar live';toast(`Não foi possível iniciar: ${err.message}`)}});
$('#live-stop').addEventListener('click',async()=>{const stop=$('#live-stop');stop.disabled=true;try{const r=await fetch(`${WORKER}/live/stop`,{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Falha ao encerrar');setLiveState(data);toast('Acompanhamento encerrado.')}catch(err){toast(`Não foi possível encerrar: ${err.message}`)}finally{stop.disabled=false}});
$('#live-url').addEventListener('input',e=>{const v=e.target.value.toLowerCase();let n='Plataforma compatível com yt-dlp';if(v.includes('youtu'))n='YouTube detectado';else if(v.includes('tiktok'))n='TikTok detectado';else if(v.includes('facebook')||v.includes('fb.watch'))n='Facebook detectado';else if(v.includes('twitch'))n='Twitch detectado';$('#platform-hint').textContent=n});
function escapeHtml(t){const p=document.createElement('p');p.textContent=t;return p.innerHTML}
function clipCard(c,i){const a=c.asset_url||'#',d=new Date(c.created_at).toLocaleDateString('pt-BR');return `<article class="clip-card"><div class="thumb">${c.thumbnail_url?`<img src="${c.thumbnail_url}" alt="">`:''}<span class="score">#${i+1} · ${Math.round(typeof c.score==='object'?(c.score.total||0):c.score||0)}</span></div><div class="clip-body"><h3>${escapeHtml(c.title||'Corte sem título')}</h3><div class="meta"><span>${Math.round(c.duration||60)}s</span><span>${d}</span></div><p class="tags">${(c.hashtags||[]).join(' ')}</p><div class="card-actions"><a href="${a}" ${a==='#'?'aria-disabled="true"':'target="_blank"'}>Assistir</a><button data-edit="${c.id}">Editar</button></div></div></article>`}
async function loadRanking(){try{const r=await fetch('data/ranking.json?ts='+Date.now());if(!r.ok)throw new Error();clips=(await r.json()).clips||[];$('#ranking-grid').innerHTML=clips.map(clipCard).join('');$('#empty-state').hidden=clips.length>0;$('#clip-select').innerHTML='<option value="">Selecione…</option>'+clips.map(c=>`<option value="${c.id}">${escapeHtml(c.title)}</option>`).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEditor(b.dataset.edit)))}catch{$('#empty-state').hidden=false;toast('Não foi possível atualizar o ranking.')}}
function openEditor(id){document.querySelector('[data-view="editor"]').click();$('#clip-select').value=id;updatePreview()}
function fallbackCaptionsUrl(c){return c?.release_tag&&c?.id?`https://github.com/${REPO}/releases/download/${c.release_tag}/${c.id}.captions.json`:''}
async function loadCaptions(c){captionTrack=[];const url=c?.captions_url||fallbackCaptionsUrl(c);if(!url){renderTimedCaption();return}try{const r=await fetch(url);if(!r.ok)throw new Error();const data=await r.json();captionTrack=Array.isArray(data.segments)?data.segments:[];renderTimedCaption()}catch{captionTrack=[];renderTimedCaption();toast('Este corte ainda não possui trilha de legendas editável.')}}
function updatePreview(){const c=clips.find(x=>x.id===$('#clip-select').value),v=$('#preview'),stage=$('#preview-stage');captionTrack=[];if(c?.asset_url){v.src=c.asset_url;stage.hidden=false;$('#video-placeholder').hidden=true;loadCaptions(c)}else{v.removeAttribute('src');stage.hidden=true;$('#video-placeholder').hidden=false}updateCaptionPreview()}
function currentCaption(){const t=$('#preview').currentTime||0;return captionTrack.find(s=>t>=Number(s.start||0)&&t<Number(s.end||0))}
function emphasisHtml(text){const safe=escapeHtml(text||'');if(!$('#caption-emphasis').checked)return safe;const terms=['absurdo','atenção','bomba','caramba','golaço','gol','histórico','impressionante','inacreditável','incrível','loucura','melhor','ninguém','polêmica','problema','segredo','sensacional','surpreendente','urgente','verdade'];const re=new RegExp(`\\b(${terms.join('|')})\\b`,'giu');return safe.replace(re,m=>`<strong style="color:${$('#highlight-color').value}">${m}</strong>`)}
function renderTimedCaption(){const box=$('#caption-preview');if($('#caption-style').value==='none'){box.hidden=true;return}box.hidden=false;const seg=currentCaption();const text=seg?.text?.trim()|| (captionTrack.length?'':'Prévia da legenda');box.innerHTML=emphasisHtml(text)}
function updateCaptionPreview(){const box=$('#caption-preview'),style=$('#caption-style').value,position=$('#caption-position').value;box.hidden=style==='none';box.style.color=$('#caption-color').value;box.style.fontSize=`${Math.round(Number($('#caption-size').value)*.42)}px`;box.dataset.position=position;box.dataset.style=style;$('#caption-size-value').textContent=$('#caption-size').value;$('#caption-controls').hidden=style==='none';renderTimedCaption()}
['caption-style','caption-color','highlight-color','caption-position','caption-size','caption-emphasis'].forEach(id=>$(`#${id}`).addEventListener('input',updateCaptionPreview));
$('#preview').addEventListener('timeupdate',renderTimedCaption);$('#preview').addEventListener('seeked',renderTimedCaption);
$('#clip-select').addEventListener('change',updatePreview);$('#refresh').addEventListener('click',loadRanking);$('#resolution').addEventListener('change',e=>$('#quality-warning').hidden=e.target.value!=='2160');
$('#edit-form').addEventListener('submit',e=>{e.preventDefault();const id=$('#clip-select').value;if(!id)return;const body=`## Corte\n${id}\n\n## Edição\n- Legenda: ${$('#caption-style').value}\n- Cor: ${$('#caption-color').value}\n- Destaque: ${$('#highlight-color').value}\n- Posição: ${$('#caption-position').value}\n- Tamanho: ${$('#caption-size').value}\n- Ênfase automática: ${$('#caption-emphasis').checked?'sim':'não'}\n- Filtro: ${$('#filter').value}\n- Resolução: ${$('#resolution').value}`;window.open(issueUrl(`[EDIT] Exportar ${id}`,body,'edit-request'),'_blank','noopener');toast('Finalize o pedido de edição no GitHub.')});
updateCaptionPreview();loadRanking();workerStatus();beginStatusPolling();
